### ISSUE TITLE
In release mode the consoles closes before I could type any command.

### ISSUE THREAD

**Issue by dsylebee** [juniorgasparotto/SysCommand#1]
In release mode the consoles closes before I could type any command.

have you ever saw this ?

**Comment by dsylebee** [comment]
nvm the issue was related to the fact that .net published my app wrapped somehow into a manifest and it would open a new app instead of using existing console.

**Comment by juniorgasparotto** [comment]
Hello

Could you send the code with the possible problem?

Remember that in console mode, you should open your ".exe" inside a prompt (MS DOS, BASH, COMEMU and etc). The prompt that opens inside VSStudio is only for simulating.

Thank you
